### ISSUE TITLE
Glow level are quite low

### ISSUE THREAD

**Issue by rsWrathionTBP** [zfedoran/solanabeach-vscode#1]
I would love to have a higher glow when using level near 1, I loved this theme tbh because I love Solana.

When you use Nigh light the glow is almost not showing

Tysm for the theme is cute and good, but need more bright!!

**Comment by zfedoran** [comment]
@rsWrathionTBP I'm happy to help but just want to make sure we're both looking at the same thing. Would you mind sharing a screenshot of what you're seeing?

**Comment by zfedoran** [comment]
Closing due to lack of response. Feel free to reopen if this is still an issue.
