### ISSUE TITLE
no glow effect when enabling

### ISSUE THREAD

**Issue by AlesyaPolik** [zfedoran/solanabeach-vscode#2]
Hi! It seems I tried a lot of things to make it work, but unfortunately, it does not make a glow effect as on the screenshot in the extension overview. Here is the screenshot from my vs code, so it looks like this after I enable Solana, it restarts the vs code, and still no glow effect. What would you suggest? Thank you.
![image](https://user-images.githubusercontent.com/66110997/221654277-bea09fc3-c720-4e78-a333-7ee6afc22cb6.png)

**Comment by zfedoran** [comment]
Hi @AlesyaPolik Thanks for trying out the theme.

Just double checking but have you enabled the glow? Using `CMD + SHIFT + P` then type in `SolanaBeach` to get the following context menu?

![image](https://user-images.githubusercontent.com/623790/221675569-9885dc79-60a3-4ab2-89f8-94a64a076f51.png)

Beyond that, what OS are you on? Common issues can stem from not having admin rights to where VS code is installed

**Comment by AlesyaPolik** [comment]
Yes, I tried to enable it exactly as you're showing. I'm using Win 10. Also tried to run under admin. Nothing helped :(

**Comment by AlesyaPolik** [comment]
In addition to what I mentioned above. Tried on another laptop where is Win 11 -  also did not work. But what is interesting is that the original 'synthwave 84' and 'synthwave 84 blues', both work on both laptops. But not Solana unfortunately.

**Comment by zfedoran** [comment]
@AlesyaPolik The latest build fixes the issue for me and hopefully should work for you as well.

Let me know if you still have issues.

**Comment by zfedoran** [comment]
Fixed in this commit: https://github.com/zfedoran/solanabeach-vscode/commit/c54cae0ef337b93b52b79e8e21bff2c82d284cb1

**Comment by AlesyaPolik** [comment]
@zfedoran  It works!!! Thank you very very much:))
